---

- name: No delay between screensaver and lock
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: int
    value: 0
    state: present

- name: Show Hidden Files
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
    state: present
- name: Use Plain Text Mode as Default in TextEdit
  community.general.osx_defaults:
    domain: com.apple.TextEdit
    key: RichText
    type: int
    value: 0
    state: present
- name: Show Path Bar
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
    state: present
- name: Enable Smooth Scrolling
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSScrollAnimationEnabled
    type: bool
    value: false
    state: present
- name: Finder Save to Disk by Default
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false
    state: present
## 0 as full name, 2 as icon
- name: Finder FastUserSwitching menu as icon
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: userMenuExtraStyle
    type: int
    value: 2
    state: present

- name: Disable automatic loading of remote content Mail.app
  community.general.osx_defaults:
    domain: com.apple.mail-shared
    key: DisableURLLoading
    type: bool
    value: true
    state: present

- name: Disable AirDrop
  community.general.osx_defaults:
    domain: com.apple.NetworkBrowser
    key: DisableAirDrop
    type: bool
    value: true
    state: present
- name: Disable iCloud drive
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false
    state: present
  when: harden_darwin_disable_iclouddrive

# - community.general.osx_defaults: domain=com.apple.Safari key=IncludeInternalDebugMenu type=bool value=true state=present
# - community.general.osx_defaults: domain=com.apple.Safari key=IncludeDevelopMenu type=bool value=true state=present
- name: Safari - disable extensions
  community.general.osx_defaults:
    domain: ~/Library/Preferences/com.apple.Safari
    key: ExtensionsEnabled
    type: bool
    value: false
    state: present
- name: Safari - Warn about fraudulent websites
  community.general.osx_defaults:
    domain: ~/Library/Preferences/com.apple.Safari
    key: WarnAboutFraudulentWebsites
    type: bool
    value: true
    state: present
- name: Safari - configure javascript
  community.general.osx_defaults:
    domain: ~/Library/Preferences/com.apple.Safari
    key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaScriptEnabled
    type: bool
    value: "{{ harden_darwin_safari_javascript | default(false) }}"
    state: present
- name: Safari - configure javascript legacy
  community.general.osx_defaults:
    domain: ~/Library/Preferences/com.apple.Safari
    key: WebKitJavaScriptEnabled
    type: bool
    value: "{{ harden_darwin_safari_javascript | default(false) }}"
    state: present
- name: Safari - configure java
  community.general.osx_defaults:
    domain: ~/Library/Preferences/com.apple.Safari
    key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabled
    type: bool
    value: false
    state: present
- name: Safari - don't open directly downloaded "safe" files
  community.general.osx_defaults:
    domain: ~/Library/Preferences/com.apple.Safari
    key: AutoOpenSafeDownloads
    type: bool
    value: false
    state: present
- name: Safari - disable autofill credit cards
  community.general.osx_defaults:
    domain: ~/Library/Preferences/com.apple.Safari
    key: AutoFillCreditCardData
    type: bool
    value: false
    state: present
- name: Safari - disable autofill from contacts
  community.general.osx_defaults:
    domain: ~/Library/Preferences/com.apple.Safari
    key: AutoFillFromAddressBook
    type: bool
    value: false
    state: present
- name: Safari - disable autofill passwords
  community.general.osx_defaults:
    domain: ~/Library/Preferences/com.apple.Safari
    key: AutoFillPasswords
    type: bool
    value: false
    state: present
- name: Safari - disable autofill others
  community.general.osx_defaults:
    domain: ~/Library/Preferences/com.apple.Safari
    key: AutoFillMiscellaneaousForms
    type: bool
    value: false
    state: present
- name: Safari - disable search engine suggestions
  community.general.osx_defaults:
    domain: ~/Library/Preferences/com.apple.Safari
    key: SuppressSearchSuggestions
    type: bool
    value: true
    state: present
- name: Safari - disable universal search
  community.general.osx_defaults:
    domain: ~/Library/Preferences/com.apple.Safari
    key: UniversalSearchEnabled
    type: bool
    value: false
    state: present
- name: Safari - DoNotTrack HTTP header
  community.general.osx_defaults:
    domain: ~/Library/Preferences/com.apple.Safari
    key: SendDoNotTrackHTTPHeader
    type: bool
    value: true
    state: present
- name: Safari - Show Full URL
  community.general.osx_defaults:
    domain: ~/Library/Preferences/com.apple.Safari
    key: ShowFullURLInSmartSearchField
    type: bool
    value: true
    state: present

- name: Photos - disable auto-launching
  community.general.osx_defaults:
    domain: com.apple.ImageCapture
    key: disableHotPlug
    type: bool
    value: yes
    state: present

## ???
# Make Crash Reporter appear as a notification
# defaults write com.apple.CrashReporter UseUNC 1
# Display the file extensions in Finder
# defaults write NSGlobalDomain AppleShowAllExtensions -bool true
# notify: killall Finder
