---

- name: Validate requested action
  ansible.builtin.fail: "FATAL! unrecognized action {{ santa_action }}"
  when: not (santa_action == 'whitelist' or santa_action == 'blacklist')

- name: "Recover file info for {{ path }}"
  ansible.builtin.stat:
    path: "{{ path }}"
    checksum_algorithm: sha256
  register: filestat

- name: Santa rule
  when: filestat.stat.exists
  block:
    - name: Santa | fileinfo check
      ansible.builtin.command: "/usr/local/bin/santactl fileinfo '{{ path }}'"
      changed_when: false
      ignore_errors: true
      register: fileinfo

    # - ansible.builtin.debug: var=fileinfo

    - name: Santa | per certificate - {{ santa_action }}
      ansible.builtin.command:  # noqa no-changed-when
        cmd: "/usr/local/bin/santactl rule --{{ santa_action }} --certificate --path '{{ path }}'"
      when: not (match + 'listed (Certificate)' in fileinfo.stdout) and santa_type == 'cert'

    - name: Santa | per hash - {{ santa_action }}
      ansible.builtin.command:  # noqa no-changed-when
        cmd: "/usr/local/bin/santactl rule --{{ santa_action }} --sha256 {{ filestat.stat.checksum }} --path '{{ path }}'"
      when: not (match + 'listed (Binary)' in fileinfo.stdout) and santa_type == 'hash'
