---

## howto fully disable/uninstall?

- name: check santa is installed
  stat: path=/var/db/santa
  register: has_santa

# OSX 10.13+: can't do it without GUI interaction...
- name: check santa kernel driver is loaded
  shell: "kextstat | grep -q com.google.santa-driver"
  changed_when: false
  ignore_errors: true
  register: santakext

- block:

    # conf?
    # /private/etc/asl/com.google.santa.asl.conf ## just logging
    # /Library/LaunchAgents/com.google.santagui.plist
    # /Library/LaunchDaemons/com.google.santad.plist
    # /private/var/log/santa.log
    # /private/var/db/santa/rules.db (sqlite3)

    - include_tasks: google-santa-whitelist.yml
      vars:
        type: cert
        path: "{{ item }}"
        action: whitelist
        match: White
      with_items: "{{ harden_darwin_santa_whitelist_cert }}"

    - include_tasks: google-santa-whitelist.yml
      vars:
        type: hash
        path: "{{ item }}"
        action: whitelist
        match: White
      with_items: "{{ harden_darwin_santa_whitelist_hash }}"

    - include_tasks: google-santa-whitelist.yml
      vars:
        type: hash
        path: "{{ item }}"
        action: blacklist
        match: Black
      with_items: "{{ harden_darwin_santa_blacklist_hash }}"

    - name: santa | blacklist users home folders path
      osx_defaults:
        domain: /var/db/santa/config.plist
        key: BlacklistRegex
        value: "{{ harden_darwin_santa_blacklist_path }}"
        state: present
      when: harden_darwin_santa_blacklist_path

    - name: santa | whitelist macports build path
      osx_defaults:
        domain: /var/db/santa/config.plist
        key: WhitelistRegex
        value: "{{ harden_darwin_santa_whitelist_path }}"
        state: present
      when: harden_darwin_santa_whitelist_path
  when: has_santa.stat.exists and santakext.rc == 0

## default is monitor mode only
## cli tool does not support anymore install, must be done by admin user in Preferences (or MDM)
- name: Set Google Santa configuration profile
  template:
    src: "{{ harden_darwin_santa_template | default('com.google.santa.mobileconfig.j2') }}"
    dest: /Users/Shared/com.google.santa.mobileconfig
    mode: '0644'

- import_tasks: google-santa-reporting.yml
