---

- name: Include version-specific variables
  include_vars: >
    MacOSX-{{ ansible_distribution_version.split('.')[0] }}.{{ ansible_distribution_version.split('.')[1] }}.yml
  when: ansible_distribution == "MacOSX"

- include: travis.yml

- include: unix.yml

- name: Darwin | Harden
  include: darwin.yml
  when: ansible_os_family == "Darwin"

- include: testing.yml
  when: harden_darwin_testing
