---

- name: Include version-specific variables - Macos 10
  include_vars: >
    MacOSX-{{ ansible_distribution_version.split('.')[0] }}.{{ ansible_distribution_version.split('.')[1] }}.yml
  when: ansible_distribution == "MacOSX" and ansible_distribution_major_version|int == 10
- name: Include version-specific variables
  include_vars: "MacOSX-{{ ansible_distribution_major_version }}.yml"
  when: ansible_distribution == "MacOSX" and ansible_distribution_major_version|int > 10

- include: travis.yml

- include: unix.yml

- name: Darwin | Harden
  include: darwin.yml
  when: ansible_os_family == "Darwin"

- include: testing.yml
  when: harden_darwin_testing
