---
## Use Apple Configurator or Macos server
## 802.1X Authentication, http://training.apple.com/pdf/WP_8021X_Authentication.pdf
## Managing OS X with Configuration Profiles, http://m.softchoice.com/cms/brands/apple/pdf/bs_apple_ad4_0513_pdf.pdf
## 10.7+: networksetup command mostly deprecated

- name: List current profile
  ansible.builtin.command: profiles -P
  changed_when: false
  ignore_errors: true
  register: profileslist

- name: Debug | profiles output
  ansible.builtin.debug:
    var: profileslist
- name: Macos mobileconfigs
  when: harden_darwin_mobileconfigs != []
  block:
    - name: Copy file to target
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ install_archives }}/{{ item | basename }}"
        mode: '0400'
        backup: yes
      with_items: "{{ harden_darwin_mobileconfigs }}"
    - name: Add mobileconfig profiles
      ansible.builtin.command: "profiles -I -F {{ install_archives }}/{{ item | basename }}"  # noqa no-changed-when
      with_items: "{{ harden_darwin_mobileconfigs }}"
      # when: "'{{ item | basename }}' not in profileslist.stdout"
