---
## https://objective-see.com/products/oversight.html

- name: Set variables for Oversight
  ansible.builtin.set_fact:
    app_name: OverSight_Installer
    app_url: https://bitbucket.org/objective-see/deploy/downloads/OverSight_1.2.0.zip
    app_checksum: 'sha1:adae7e8a2d4f78489205d6b0c3017c3ebf733f6f'

- name: download {{ app_name }}
  ansible.builtin.get_url:
    url: "{{ app_url }}"
    dest: "{{ install_archives }}/{{ app_url | basename }}"
    mode: '0644'
    checksum: "{{ app_checksum }}"
    validate_certs: "{{ harden_darwin_bitbucket_sslcert_validate | default(true) }}"
  become: yes

- name: decompress {{ app_name }}
  ansible.builtin.unarchive:
    src: "{{ install_archives }}/{{ app_url | basename }}"
    dest: "{{ install_archives }}"
    mode: '0755'
    creates: "{{ install_archives }}/{{ app_name }}.app/Contents/MacOS/{{ app_name }}"
  become: yes

- block:
    - include_tasks: google-santa-whitelist.yml
      vars:
        type: hash
        path: "{{ item }}"
        action: whitelist
        match: White
      with_items:
        - "{{ install_archives }}/{{ app_name }}.app/Contents/MacOS/{{ app_name }}"
  when: harden_darwin_santa is defined and harden_darwin_santa and harden_darwin_santa_mode == 2

## FIXME! always return 'install ok' and rc = 0
- name: install oversight
  ansible.builtin.command: "{{ install_archives }}/{{ app_name }}.app/Contents/MacOS/{{ app_name }} -install"
  args:
    creates: "/Applications/OverSight.app/Contents/MacOS/OverSight"
  become: yes

- block:
    - include_tasks: google-santa-whitelist.yml
      vars:
        type: hash
        path: "{{ item }}"
        action: whitelist
        match: White
      with_items:
        - "/Applications/OverSight.app/Contents/MacOS/OverSight"
  when: harden_darwin_santa is defined and harden_darwin_santa and harden_darwin_santa_mode == 2
