---
## https://objective-see.com/products/oversight.html

- name: Set variables for Oversight
  ansible.builtin.set_fact:
    app_name: 'OverSight Installer'
    app_url: https://github.com/objective-see/OverSight/releases/download/v2.0.1/OverSight_2.0.1.zip
    app_checksum: 'sha256:e19d4da26aeba29343d3bdc33643c03b925ed29a13bc71eae46c5999b654b843'

- name: Download {{ app_name }}
  ansible.builtin.get_url:
    url: "{{ app_url }}"
    dest: "{{ install_archives }}/{{ app_url | basename }}"
    mode: '0644'
    checksum: "{{ app_checksum }}"
    validate_certs: "{{ harden_darwin_bitbucket_sslcert_validate | default(true) }}"
  become: yes

- name: Decompress {{ app_name }}
  ansible.builtin.unarchive:
    src: "{{ install_archives }}/{{ app_url | basename }}"
    dest: "{{ install_archives }}"
    mode: '0755'
    creates: "{{ install_archives }}/{{ app_name }}.app/Contents/MacOS/{{ app_name }}"
  become: yes

- name: Ensure app is allowed by Google Santa
  when: harden_darwin_santa is defined and harden_darwin_santa and harden_darwin_santa_mode == 2
  block:
    - name: Include google-santa-whitelist
      ansible.builtin.include_tasks: google-santa-whitelist.yml
      vars:
        santa_type: hash
        path: "{{ item }}"
        santa_action: whitelist
        match: White
      with_items:
        - "{{ install_archives }}/{{ app_name }}.app/Contents/MacOS/{{ app_name }}"

## FIXME! always return 'install ok' and rc = 0
- name: Install oversight
  ansible.builtin.command: "\"{{ install_archives }}/{{ app_name }}.app/Contents/MacOS/{{ app_name }}\" -install"
  args:
    creates: "/Applications/OverSight.app/Contents/MacOS/OverSight"
  become: yes

- name: Ensure app is allowed by Google Santa
  when: harden_darwin_santa is defined and harden_darwin_santa and harden_darwin_santa_mode == 2
  block:
    - name: Include google-santa-whitelist
      ansible.builtin.include_tasks: google-santa-whitelist.yml
      vars:
        santa_type: hash
        path: "{{ item }}"
        santa_action: whitelist
        match: White
      with_items:
        - "/Applications/OverSight.app/Contents/MacOS/OverSight"
