---

- name: Set variables for KnockKnock
  ansible.builtin.set_fact:
    app_name: KnockKnock
    app_url: https://bitbucket.org/objective-see/deploy/downloads/KnockKnock_1.9.3.zip
    app_checksum: 'sha1:a31528b825759fb7fc0e9402572ddda0fe972009'

- name: download {{ app_name }}
  ansible.builtin.get_url:
    url: "{{ app_url }}"
    dest: "{{ install_archives }}/{{ app_url | basename }}"
    mode: '0644'
    checksum: "{{ app_checksum }}"
    validate_certs: "{{ harden_darwin_bitbucket_sslcert_validate | default(true) }}"
  become: yes

- name: decompress {{ app_name }}
  ansible.builtin.unarchive:
    src: "{{ install_archives }}/{{ app_url | basename }}"
    dest: "{{ install_archives }}"
    mode: '0755'
    creates: "{{ install_archives }}/{{ app_name }}.app/Contents/MacOS/{{ app_name }}"
  become: yes

- block:
    - include_tasks: google-santa-whitelist.yml
      vars:
        type: hash
        path: "{{ item }}"
        action: whitelist
        match: White
      with_items:
        - "{{ install_archives }}/{{ app_name }}.app/Contents/MacOS/{{ app_name }}"
  when: harden_darwin_santa is defined and harden_darwin_santa and harden_darwin_santa_mode == 2
