---

- name: Inspec
  block:
    - name: testing | run macos-baseline
      ansible.builtin.shell: >
        /usr/local/bin/inspec exec https://github.com/juju4/macos-baseline/archive/master.tar.gz |
            tee /var/log/inspec.log
      ignore_errors: true
      register: inspeclog
      args:
        creates: /var/log/inspec.log
    - name: Debug | inspec output
      ansible.builtin.debug: var=inspeclog.stdout_lines

  when: harden_darwin_testing_inspec

- import_tasks: testing-privesc.yml
  when: harden_darwin_testing_privesc

- import_tasks: testing-speculative.yml
  when: harden_darwin_testing_speculative
