---

- name: Get state of interface - {{ interface }}
  ansible.builtin.command: "networksetup -getproxyautodiscovery \"{{ interface }}\""
  register: ifstate
  changed_when: false
  ignore_errors: true

- name: Turn off wpad
  ansible.builtin.command:  # noqa no-changed-when
    cmd: "networksetup -setproxyautodiscovery \"{{ interface }}\" off"
  become: yes
  when: ifstate.stdout.find("Off") == -1
