---

- name: Get list of network devices
  ansible.builtin.shell: "networksetup -listallnetworkservices | grep -v 'denotes that a network service is disabled'"  # noqa risky-shell-pipe
  become: yes
  register: netlist
  changed_when: false

- name: Include wpad-disable-if
  ansible.builtin.include_tasks: wpad-disable-if.yml
  vars:
    interface: "{{ item }}"
  with_items: "{{ netlist.stdout_lines }}"
