---

- name: get state of interface "{{ interface }}"
  command: "networksetup -getproxyautodiscovery \"{{ interface }}\""
  register: ifstate
  changed_when: false
  ignore_errors: true

- name: turn off wpad
  command: "networksetup -setproxyautodiscovery \"{{ interface }}\" off"
  become: yes
  when: ifstate.stdout.find("Off") == -1
