---

## not sure it is needed, as sshd is managed by launchd/inetd-like
- name: Restart sshd
  # ansible.builtin.service: name={{ ssh_svc }} state=restarted
  ansible.builtin.command:  # noqa no-changed-when
    cmd: |
      launchctl stop -w /System/Library/LaunchDaemons/ssh.plist;
      launchctl start -w /System/Library/LaunchDaemons/ssh.plist
  failed_when: false

- name: Reload fstab
  ansible.builtin.shell:  # noqa no-changed-when
    cmd: "umount -a; mount -a"
  failed_when: false

- name: Kill osx bluetooth
  ansible.builtin.command:  # noqa no-changed-when
    cmd: "killall -HUP blued"
  failed_when: false

- name: Restart osquery
  # ansible.builtin.service: name=osqueryd state=restarted
  ansible.builtin.command:  # noqa no-changed-when
    cmd: >
      launchctl stop -w /Library/LaunchDaemons/com.facebook.osqueryd.plist;
      launchctl start -w /Library/LaunchDaemons/com.facebook.osqueryd.plist
  failed_when: false

## seems to always return 3 and not restarting anything
- name: Restart santa
  ansible.builtin.command:  # noqa no-changed-when
    cmd: >
      launchctl stop -w /Library/LaunchDaemons/com.google.santad.plist;
      launchctl start -w /Library/LaunchDaemons/com.google.santad.plist
  failed_when: false

- name: Restart auditd
  ansible.builtin.command:  # noqa no-changed-when
    cmd: >
      launchctl stop -w /System/Library/LaunchDaemons/com.apple.auditd.plist;
      launchctl start -w /System/Library/LaunchDaemons/com.apple.auditd.plist
  failed_when: false

- name: Reload pf
  ansible.builtin.command:  # noqa no-changed-when
    cmd: "pfctl -f /etc/pf.conf"

- name: USB+Firewire | Force refresh of Extensions cache at next reboot
  ansible.builtin.file:
    dest: /System/Library/Extensions
    mode: '0644'
    state: touch
